import { Product, StockMovement, Category, Supplier } from './types';

export const mockCategories: Category[] = [
  { id: '1', name: 'Eletrônicos', description: 'Produtos eletrônicos em geral' },
  { id: '2', name: 'Roupas', description: 'Vestuário e acessórios' },
  { id: '3', name: 'Livros', description: 'Livros e material de leitura' },
  { id: '4', name: 'Casa & Jardim', description: 'Produtos para casa e jardim' },
  { id: '5', name: 'Esportes', description: 'Equipamentos esportivos' },
];

export const mockSuppliers: Supplier[] = [
  {
    id: '1',
    name: 'TechSupply Ltda',
    contact: 'João Silva',
    email: 'joao@techsupply.com',
    phone: '(11) 9999-8888'
  },
  {
    id: '2',
    name: 'Fashion World',
    contact: 'Maria Santos',
    email: 'maria@fashionworld.com',
    phone: '(11) 8888-7777'
  },
  {
    id: '3',
    name: 'Editora Brasil',
    contact: 'Carlos Oliveira',
    email: 'carlos@editorabrasil.com',
    phone: '(11) 7777-6666'
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Smartphone Samsung Galaxy',
    description: 'Smartphone Android com 128GB',
    sku: 'SMSG-128-BLK',
    category: 'Eletrônicos',
    price: 1299.99,
    stockQuantity: 25,
    minStockLevel: 10,
    maxStockLevel: 100,
    supplier: 'TechSupply Ltda',
    location: 'Estoque A1',
    lastUpdated: new Date('2025-05-30'),
    createdAt: new Date('2025-01-15'),
  },
  {
    id: '2',
    name: 'Camiseta Nike Dri-FIT',
    description: 'Camiseta esportiva masculina',
    sku: 'NIKE-DRI-M-BLK',
    category: 'Roupas',
    price: 89.99,
    stockQuantity: 5,
    minStockLevel: 20,
    maxStockLevel: 200,
    supplier: 'Fashion World',
    location: 'Estoque B2',
    lastUpdated: new Date('2025-06-01'),
    createdAt: new Date('2025-02-10'),
  },
  {
    id: '3',
    name: 'Livro "Clean Code"',
    description: 'Livro sobre programação limpa',
    sku: 'BOOK-CC-ENG',
    category: 'Livros',
    price: 79.90,
    stockQuantity: 15,
    minStockLevel: 5,
    maxStockLevel: 50,
    supplier: 'Editora Brasil',
    location: 'Estoque C1',
    lastUpdated: new Date('2025-05-28'),
    createdAt: new Date('2025-03-05'),
  },
  {
    id: '4',
    name: 'Notebook Dell Inspiron',
    description: 'Notebook Intel i5, 8GB RAM, 256GB SSD',
    sku: 'DELL-INSP-I5',
    category: 'Eletrônicos',
    price: 2499.99,
    stockQuantity: 8,
    minStockLevel: 5,
    maxStockLevel: 30,
    supplier: 'TechSupply Ltda',
    location: 'Estoque A2',
    lastUpdated: new Date('2025-06-02'),
    createdAt: new Date('2025-04-01'),
  },
  {
    id: '5',
    name: 'Tênis Adidas Running',
    description: 'Tênis para corrida masculino',
    sku: 'ADIDAS-RUN-M-42',
    category: 'Esportes',
    price: 299.99,
    stockQuantity: 0,
    minStockLevel: 10,
    maxStockLevel: 80,
    supplier: 'Fashion World',
    location: 'Estoque B3',
    lastUpdated: new Date('2025-06-01'),
    createdAt: new Date('2025-01-20'),
  },
];

export const mockStockMovements: StockMovement[] = [
  // Movimentações dos últimos 7 dias
  {
    id: '1',
    productId: '1',
    type: 'IN',
    quantity: 50,
    reason: 'Compra de fornecedor',
    userId: 'admin',
    timestamp: new Date('2025-06-02'),
    reference: 'PO-2025-001',
  },
  {
    id: '2',
    productId: '1',
    type: 'OUT',
    quantity: 25,
    reason: 'Venda',
    userId: 'vendedor1',
    timestamp: new Date('2025-06-01'),
    reference: 'SALE-2025-123',
  },
  {
    id: '3',
    productId: '2',
    type: 'OUT',
    quantity: 15,
    reason: 'Venda',
    userId: 'vendedor2',
    timestamp: new Date('2025-06-01'),
    reference: 'SALE-2025-124',
  },
  {
    id: '4',
    productId: '3',
    type: 'IN',
    quantity: 20,
    reason: 'Reposição de estoque',
    userId: 'admin',
    timestamp: new Date('2025-05-31'),
    reference: 'PO-2025-002',
  },
  {
    id: '5',
    productId: '2',
    type: 'IN',
    quantity: 30,
    reason: 'Compra de fornecedor',
    userId: 'admin',
    timestamp: new Date('2025-05-30'),
    reference: 'PO-2025-003',
  },
  {
    id: '6',
    productId: '4',
    type: 'OUT',
    quantity: 5,
    reason: 'Venda',
    userId: 'vendedor1',
    timestamp: new Date('2025-05-29'),
    reference: 'SALE-2025-125',
  },
  {
    id: '7',
    productId: '1',
    type: 'OUT',
    quantity: 10,
    reason: 'Venda',
    userId: 'vendedor2',
    timestamp: new Date('2025-05-28'),
    reference: 'SALE-2025-126',
  },
  {
    id: '8',
    productId: '3',
    type: 'OUT',
    quantity: 8,
    reason: 'Venda',
    userId: 'vendedor1',
    timestamp: new Date('2025-05-27'),
    reference: 'SALE-2025-127',
  },
  // Movimentações mensais anteriores
  {
    id: '9',
    productId: '2',
    type: 'IN',
    quantity: 100,
    reason: 'Estoque inicial',
    userId: 'admin',
    timestamp: new Date('2025-05-15'),
    reference: 'PO-2025-004',
  },
  {
    id: '10',
    productId: '1',
    type: 'IN',
    quantity: 75,
    reason: 'Compra grande lote',
    userId: 'admin',
    timestamp: new Date('2025-04-20'),
    reference: 'PO-2025-005',
  },
  {
    id: '11',
    productId: '4',
    type: 'IN',
    quantity: 15,
    reason: 'Reposição',
    userId: 'admin',
    timestamp: new Date('2025-04-15'),
    reference: 'PO-2025-006',
  },
  {
    id: '12',
    productId: '5',
    type: 'IN',
    quantity: 50,
    reason: 'Estoque inicial',
    userId: 'admin',
    timestamp: new Date('2025-03-10'),
    reference: 'PO-2025-007',
  },
];
